# Generated by Django 3.2.6 on 2021-10-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdesk', '0003_auto_20210910_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='display_picture',
            field=models.FileField(max_length=254, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='member',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
