# Generated by Django 3.2.6 on 2021-10-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workdesk', '0004_auto_20211021_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='display_picture',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
